name: ldp_gateway
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.5
  flutter_spinkit: ^5.1.0
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  fluttertoast: ^8.0.9
  lazy_load_scrollview: ^1.3.0
  http: ^0.13.4
  push_notification: ^1.1.1
  device_info_plus: ^3.2.3
  sqflite: ^2.0.2
  flutter_background_service: ^1.0.4
  carousel_slider: ^4.1.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  web3dart: 2.3.5
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/coins/
    - assets/icons/

  fonts:
    - family: Averta
      fonts:
        - asset: assets/fonts/Averta-Regular.ttf
        - asset: assets/fonts/Averta-Bold.ttf


